import type { CatalogItem } from "@/types/catalog";
import dune from "@/assets/dune.jpg";
import lastOfUs from "@/assets/The-Last-of-Us.jpg";

const posters = import.meta.glob<string>("../assets/catalog/*.jpg", {
  eager: true,
  query: "?url",
  import: "default",
});
export const seriesCatalog: CatalogItem[] = [
  {
    id: "breaking-bad",
    title: "Breaking Bad",
    persianTitle: "بریکینگ بد",
    type: "series",
    year: 2008,
    rating: 9.5,
    genres: ["درام", "جنایی"],
    episodes: 62,
    poster: posters["../assets/catalog/breaking-bad.jpg"] ?? "",
  },
  {
    id: "game-of-thrones",
    title: "Game of Thrones",
    persianTitle: "بازی تاج و تخت",
    type: "series",
    year: 2011,
    rating: 9.2,
    genres: ["درام", "فانتزی"],
    episodes: 73,
    poster: posters["../assets/catalog/game-of-thrones.jpg"] ?? "",
  },
  {
    id: "the-last-of-us",
    title: "The Last of Us",
    persianTitle: "آخرین بازمانده از ما",
    type: "series",
    year: 2023,
    rating: 8.8,
    genres: ["درام", "علمی‌تخیلی"],
    episodes: 16,
    poster: lastOfUs,
  },
  {
    id: "stranger-things",
    title: "Stranger Things",
    persianTitle: "چیزهای عجیب",
    type: "series",
    year: 2016,
    rating: 8.7,
    genres: ["علمی‌تخیلی", "ترسناک"],
    episodes: 34,
    poster: posters["../assets/catalog/stranger-things.jpg"] ?? "",
  },
  {
    id: "wednesday",
    title: "Wednesday",
    persianTitle: "ونزدی",
    type: "series",
    year: 2022,
    rating: 8.0,
    genres: ["فانتزی", "کمدی"],
    episodes: 8,
    poster: posters["../assets/catalog/wednesday.jpg"] ?? "",
  },
  {
    id: "peaky-blinders",
    title: "Peaky Blinders",
    persianTitle: "پیکی بلایندرز",
    type: "series",
    year: 2013,
    rating: 8.8,
    genres: ["درام", "جنایی"],
    episodes: 36,
    poster: posters["../assets/catalog/peaky-blinders.jpg"] ?? "",
  },
  {
    id: "the-mandalorian",
    title: "The Mandalorian",
    persianTitle: "مندلورین",
    type: "series",
    year: 2019,
    rating: 8.7,
    genres: ["علمی‌تخیلی", "اکشن"],
    episodes: 24,
    poster: posters["../assets/catalog/the-mandalorian.jpg"] ?? "",
  },
  {
    id: "loki",
    title: "Loki",
    persianTitle: "لوکی",
    type: "series",
    year: 2021,
    rating: 8.2,
    genres: ["فانتزی", "اکشن"],
    episodes: 12,
    poster: posters["../assets/catalog/loki.jpg"] ?? "",
  },
  {
    id: "arcane",
    title: "Arcane",
    persianTitle: "آرکین",
    type: "series",
    year: 2021,
    rating: 8.6,
    genres: ["انیمیشن", "فانتزی"],
    episodes: 18,
    poster: posters["../assets/catalog/arcane.jpg"] ?? "",
  },
];
export const sampleSearchResults: CatalogItem[] = [
  {
    id: "dune-part-two",
    title: "Dune: Part Two",
    persianTitle: "تلماسه قسمت دوم",
    type: "movie",
    year: 2024,
    rating: 8.6,
    genres: ["علمی‌تخیلی", "ماجراجویی"],
    duration: 166,
    poster: dune,
  },
  {
    id: "dune",
    title: "Dune",
    persianTitle: "تلماسه",
    type: "movie",
    year: 2021,
    rating: 8.0,
    genres: ["علمی‌تخیلی", "ماجراجویی"],
    duration: 155,
    poster: posters["../assets/catalog/dune.jpg"] ?? "",
  },
  {
    id: "dune-prophecy",
    title: "Dune: Prophecy",
    persianTitle: "تلماسه پیشگویی",
    type: "series",
    year: 2024,
    rating: 7.3,
    genres: ["علمی‌تخیلی", "درام"],
    episodes: 6,
    poster: posters["../assets/catalog/dune-prophecy.jpg"] ?? "",
  },
];
